"""The concrete sweep: which types to ask for, and the commands to run.

Type choice is not a detail.  The Tallinn sweep searched ``restaurant`` alone
and missed 22 of 25 curated places -- not because the circles were wrong but
because Google does not consider a cafe, a bakery, a pub or a bar to be a
restaurant, and returns a place only if the requested type appears in that
place's own type list.  Miss rates before the fix: coffee 75%, cafes 71%,
bakery 56%, pub 46%, against restaurant 7%.

Berlin needs everything Tallinn needed plus what Berlin actually eats at: the
Imbiss and the Doener counter type as ``fast_food_restaurant`` or
``meal_takeaway``, the Baeckerei as ``bakery``, the Biergarten as ``bar`` or
``pub``, and Berlin's cafe culture spans ``cafe``, ``coffee_shop`` and
``brunch_restaurant``.
"""

from __future__ import annotations

from typing import List, Optional

from .cost import DistrictPlan, Plan

# The Tallinn list, which took Tastebuds coverage from 66% to 95%...
TALLINN_TYPES: List[str] = [
    "restaurant", "cafe", "coffee_shop", "bakery", "bar", "pub", "wine_bar",
    "meal_takeaway", "ice_cream_shop", "dessert_shop", "sandwich_shop",
    "tea_house", "brewery", "chocolate_shop", "confectionery", "donut_shop",
    "deli",
]

# ...plus the shapes Berlin's food scene actually takes.
BERLIN_EXTRA_TYPES: List[str] = [
    "fast_food_restaurant", "brunch_restaurant", "bar_and_grill",
    "buffet_restaurant", "food_court", "bagel_shop", "juice_shop",
    "meal_delivery", "diner", "steak_house", "vegan_restaurant",
    "vegetarian_restaurant",
]

TYPES: List[str] = TALLINN_TYPES + BERLIN_EXTRA_TYPES


def types_argument() -> str:
    return ",".join(TYPES)


def scan_commands(plan: DistrictPlan, min_reviews: int, tier: str,
                  budget: Optional[int] = None) -> List[str]:
    """One allrestaurants invocation per rectangle in a borough."""
    out = []
    for tile in plan.district.tiles:
        south, west, north, east = tile
        parts = [
            "allrestaurants scan",
            f'--bbox "{south},{west},{north},{east}"',
            f"--cell-radius-m {plan.cell_radius_m:.0f}",
            f"--min-reviews {min_reviews}",
            f"--tier {tier}",
            '--types "$TYPES"',
        ]
        if budget:
            parts.append(f"--max-requests {budget}")
        out.append(" \\\n    ".join(parts))
    return out


def probe_command(plan: DistrictPlan, min_reviews: int, tier: str) -> str:
    """A handful of calls that measure a borough's density before committing.

    Twelve of these on Tallinn's districts cut a 286-call estimate to 171 and
    cost $0.42.  The thing they measure is the weakest of the 20 results: if
    even it clears the review bar the circle is hiding more and will split; if
    it has 6 reviews the tail is already in view and the circle stops.
    """
    lat, lng = plan.district.center
    return (
        f'allrestaurants check --center "{lat},{lng}" '
        f'--types "$TYPES" --tier {tier}'
    )


def script(plan: Plan, tier: str) -> str:
    """A runnable sweep script: cheapest boroughs first, so a budget stops late."""
    lines = [
        "#!/usr/bin/env bash",
        "# Sweep Berlin borough by borough.  Generated by `allberlin commands`.",
        "#",
        "# Ordered cheapest first on purpose: if the budget or your nerve runs",
        "# out, what is left unswept is the expensive part you can decide about",
        "# separately, not a random half of the city.  Every borough is",
        "# resumable -- rerun the identical command and it picks up where it",
        "# stopped rather than paying Google twice.",
        "set -euo pipefail",
        "",
        f'TYPES="{types_argument()}"',
        "",
    ]
    for p in sorted(plan.districts, key=lambda p: p.total_calls):
        # A per-borough cap, generous enough not to bite in the ordinary case
        # and tight enough that a wrong density estimate costs one borough's
        # worth of calls rather than the whole budget.  The sweep stops
        # cleanly on it and resumes where it stopped.
        cap = int(p.planning_calls / max(1, len(p.district.tiles)))
        lines.append(f"# {p.district.name}: ~{p.total_calls:.0f} calls, "
                     f"~{p.places:.0f} places expected, "
                     f"{p.swept_km2:.0f} km2 in {len(p.district.tiles)} tile(s)")
        lines.extend(scan_commands(p, plan.min_reviews, tier, budget=cap))
        lines.append("")
    lines += [
        "allrestaurants stats",
        "allrestaurants export --format csv --out exports/berlin_restaurants.csv",
    ]
    return "\n".join(lines)
